### ISSUE TITLE
J'obtiens une simulation de 0

### ISSUE THREAD

**Issue by jilljenn** [openfisca/jupyter#1]
Bonjour, j'espère que je suis sur le bon repo.

J'ai tenté https://jupyter.openfisca.fr, mais je n'aboutis qu'à des simulations de 0, alors que d'après le GitBook, l'une des valeurs ne devrait pas être nulle.

**Comment by benjello** [comment]
Bonjour, merci de tester openfisca. La réforme à peut-être été intégrée dans la législation d'où l'absence de différence entre réforme et référence. Nous allons essayer de mettre en place un exemple plus pertinent rapidement. 
@cbenz @adrienpacifico

**Comment by jilljenn** [comment]
Vous voulez dire que le gouvernement a mergé la pull request ? :D

**Comment by MattiSG** [comment]
Ce n'était pas le bon repo  :wink:
